//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteASP.Usuario {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModeloUsuario", Namespace="http://schemas.datacontract.org/2004/07/ModeloWCF")]
    [System.SerializableAttribute()]
    public partial class ModeloUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contrasenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string direccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nivelAccesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellido {
            get {
                return this.apellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidoField, value) != true)) {
                    this.apellidoField = value;
                    this.RaisePropertyChanged("apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                if ((object.ReferenceEquals(this.contrasenaField, value) != true)) {
                    this.contrasenaField = value;
                    this.RaisePropertyChanged("contrasena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                if ((object.ReferenceEquals(this.direccionField, value) != true)) {
                    this.direccionField = value;
                    this.RaisePropertyChanged("direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nivelAcceso {
            get {
                return this.nivelAccesoField;
            }
            set {
                if ((object.ReferenceEquals(this.nivelAccesoField, value) != true)) {
                    this.nivelAccesoField = value;
                    this.RaisePropertyChanged("nivelAcceso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreUsuario {
            get {
                return this.nombreUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreUsuarioField, value) != true)) {
                    this.nombreUsuarioField = value;
                    this.RaisePropertyChanged("nombreUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Usuario.IUsuario")]
    public interface IUsuario {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/Login", ReplyAction="http://tempuri.org/IUsuario/LoginResponse")]
        ClienteASP.Usuario.ModeloUsuario Login(string nombreUsuario, string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/ObtenerTodosUsuarios", ReplyAction="http://tempuri.org/IUsuario/ObtenerTodosUsuariosResponse")]
        ClienteASP.Usuario.ModeloUsuario[] ObtenerTodosUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/ObtenerUsuariosConElNombre", ReplyAction="http://tempuri.org/IUsuario/ObtenerUsuariosConElNombreResponse")]
        ClienteASP.Usuario.ModeloUsuario[] ObtenerUsuariosConElNombre(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/ObtenerUsuariosConElApellido", ReplyAction="http://tempuri.org/IUsuario/ObtenerUsuariosConElApellidoResponse")]
        ClienteASP.Usuario.ModeloUsuario[] ObtenerUsuariosConElApellido(string apellido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/insertarUsuario", ReplyAction="http://tempuri.org/IUsuario/insertarUsuarioResponse")]
        bool insertarUsuario(string nombre, string apellido, string direccion, string nombreusuario, string contrasena, string nivelacceso, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/buscarUsuarioPorNombreUsuario", ReplyAction="http://tempuri.org/IUsuario/buscarUsuarioPorNombreUsuarioResponse")]
        bool buscarUsuarioPorNombreUsuario(string nombreUsuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsuarioChannel : ClienteASP.Usuario.IUsuario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuarioClient : System.ServiceModel.ClientBase<ClienteASP.Usuario.IUsuario>, ClienteASP.Usuario.IUsuario {
        
        public UsuarioClient() {
        }
        
        public UsuarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClienteASP.Usuario.ModeloUsuario Login(string nombreUsuario, string contrasena) {
            return base.Channel.Login(nombreUsuario, contrasena);
        }
        
        public ClienteASP.Usuario.ModeloUsuario[] ObtenerTodosUsuarios() {
            return base.Channel.ObtenerTodosUsuarios();
        }
        
        public ClienteASP.Usuario.ModeloUsuario[] ObtenerUsuariosConElNombre(string nombre) {
            return base.Channel.ObtenerUsuariosConElNombre(nombre);
        }
        
        public ClienteASP.Usuario.ModeloUsuario[] ObtenerUsuariosConElApellido(string apellido) {
            return base.Channel.ObtenerUsuariosConElApellido(apellido);
        }
        
        public bool insertarUsuario(string nombre, string apellido, string direccion, string nombreusuario, string contrasena, string nivelacceso, string email) {
            return base.Channel.insertarUsuario(nombre, apellido, direccion, nombreusuario, contrasena, nivelacceso, email);
        }
        
        public bool buscarUsuarioPorNombreUsuario(string nombreUsuario) {
            return base.Channel.buscarUsuarioPorNombreUsuario(nombreUsuario);
        }
    }
}
