//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteASP.Oferta {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModeloOferta", Namespace="http://schemas.datacontract.org/2004/07/ModeloWCF")]
    [System.SerializableAttribute()]
    public partial class ModeloOferta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float cantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double idOfertaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float precioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteASP.Oferta.ModeloProducto productoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipoMonedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool tomadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteASP.Oferta.ModeloUsuario usuarioSubastaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool vencidaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float cantidad {
            get {
                return this.cantidadField;
            }
            set {
                if ((this.cantidadField.Equals(value) != true)) {
                    this.cantidadField = value;
                    this.RaisePropertyChanged("cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((this.fechaField.Equals(value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double idOferta {
            get {
                return this.idOfertaField;
            }
            set {
                if ((this.idOfertaField.Equals(value) != true)) {
                    this.idOfertaField = value;
                    this.RaisePropertyChanged("idOferta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float precio {
            get {
                return this.precioField;
            }
            set {
                if ((this.precioField.Equals(value) != true)) {
                    this.precioField = value;
                    this.RaisePropertyChanged("precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteASP.Oferta.ModeloProducto producto {
            get {
                return this.productoField;
            }
            set {
                if ((object.ReferenceEquals(this.productoField, value) != true)) {
                    this.productoField = value;
                    this.RaisePropertyChanged("producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipoMoneda {
            get {
                return this.tipoMonedaField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoMonedaField, value) != true)) {
                    this.tipoMonedaField = value;
                    this.RaisePropertyChanged("tipoMoneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool tomada {
            get {
                return this.tomadaField;
            }
            set {
                if ((this.tomadaField.Equals(value) != true)) {
                    this.tomadaField = value;
                    this.RaisePropertyChanged("tomada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteASP.Oferta.ModeloUsuario usuarioSubasta {
            get {
                return this.usuarioSubastaField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioSubastaField, value) != true)) {
                    this.usuarioSubastaField = value;
                    this.RaisePropertyChanged("usuarioSubasta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool vencida {
            get {
                return this.vencidaField;
            }
            set {
                if ((this.vencidaField.Equals(value) != true)) {
                    this.vencidaField = value;
                    this.RaisePropertyChanged("vencida");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModeloProducto", Namespace="http://schemas.datacontract.org/2004/07/ModeloWCF")]
    [System.SerializableAttribute()]
    public partial class ModeloProducto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteASP.Oferta.ModeloUsuario UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float cantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string detalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool evaluadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaOfertaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaVencimientoOfertaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double idProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] imagenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string unidadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteASP.Oferta.ModeloUsuario Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float cantidad {
            get {
                return this.cantidadField;
            }
            set {
                if ((this.cantidadField.Equals(value) != true)) {
                    this.cantidadField = value;
                    this.RaisePropertyChanged("cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string detalle {
            get {
                return this.detalleField;
            }
            set {
                if ((object.ReferenceEquals(this.detalleField, value) != true)) {
                    this.detalleField = value;
                    this.RaisePropertyChanged("detalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool evaluado {
            get {
                return this.evaluadoField;
            }
            set {
                if ((this.evaluadoField.Equals(value) != true)) {
                    this.evaluadoField = value;
                    this.RaisePropertyChanged("evaluado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaOferta {
            get {
                return this.fechaOfertaField;
            }
            set {
                if ((this.fechaOfertaField.Equals(value) != true)) {
                    this.fechaOfertaField = value;
                    this.RaisePropertyChanged("fechaOferta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaVencimientoOferta {
            get {
                return this.fechaVencimientoOfertaField;
            }
            set {
                if ((this.fechaVencimientoOfertaField.Equals(value) != true)) {
                    this.fechaVencimientoOfertaField = value;
                    this.RaisePropertyChanged("fechaVencimientoOferta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double idProducto {
            get {
                return this.idProductoField;
            }
            set {
                if ((this.idProductoField.Equals(value) != true)) {
                    this.idProductoField = value;
                    this.RaisePropertyChanged("idProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] imagen {
            get {
                return this.imagenField;
            }
            set {
                if ((object.ReferenceEquals(this.imagenField, value) != true)) {
                    this.imagenField = value;
                    this.RaisePropertyChanged("imagen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string unidad {
            get {
                return this.unidadField;
            }
            set {
                if ((object.ReferenceEquals(this.unidadField, value) != true)) {
                    this.unidadField = value;
                    this.RaisePropertyChanged("unidad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModeloUsuario", Namespace="http://schemas.datacontract.org/2004/07/ModeloWCF")]
    [System.SerializableAttribute()]
    public partial class ModeloUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contrasenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string direccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nivelAccesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellido {
            get {
                return this.apellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidoField, value) != true)) {
                    this.apellidoField = value;
                    this.RaisePropertyChanged("apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                if ((object.ReferenceEquals(this.contrasenaField, value) != true)) {
                    this.contrasenaField = value;
                    this.RaisePropertyChanged("contrasena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                if ((object.ReferenceEquals(this.direccionField, value) != true)) {
                    this.direccionField = value;
                    this.RaisePropertyChanged("direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nivelAcceso {
            get {
                return this.nivelAccesoField;
            }
            set {
                if ((object.ReferenceEquals(this.nivelAccesoField, value) != true)) {
                    this.nivelAccesoField = value;
                    this.RaisePropertyChanged("nivelAcceso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreUsuario {
            get {
                return this.nombreUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreUsuarioField, value) != true)) {
                    this.nombreUsuarioField = value;
                    this.RaisePropertyChanged("nombreUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Oferta.IOferta")]
    public interface IOferta {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOferta/OfrecerOferta", ReplyAction="http://tempuri.org/IOferta/OfrecerOfertaResponse")]
        void OfrecerOferta(float cantidad, float precio, double idproducto, string nombreUsuario, string tipoMoneda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOferta/VerMisOfertas", ReplyAction="http://tempuri.org/IOferta/VerMisOfertasResponse")]
        ClienteASP.Oferta.ModeloOferta[] VerMisOfertas(string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOferta/VerOfertasDelProducto", ReplyAction="http://tempuri.org/IOferta/VerOfertasDelProductoResponse")]
        ClienteASP.Oferta.ModeloOferta[] VerOfertasDelProducto(double idProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOferta/EscogerEstasOfertas", ReplyAction="http://tempuri.org/IOferta/EscogerEstasOfertasResponse")]
        void EscogerEstasOfertas(ClienteASP.Oferta.ModeloOferta[] ofertasGanadoras, ClienteASP.Oferta.ModeloOferta[] ofertasPerdedoras);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOfertaChannel : ClienteASP.Oferta.IOferta, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OfertaClient : System.ServiceModel.ClientBase<ClienteASP.Oferta.IOferta>, ClienteASP.Oferta.IOferta {
        
        public OfertaClient() {
        }
        
        public OfertaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OfertaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OfertaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OfertaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void OfrecerOferta(float cantidad, float precio, double idproducto, string nombreUsuario, string tipoMoneda) {
            base.Channel.OfrecerOferta(cantidad, precio, idproducto, nombreUsuario, tipoMoneda);
        }
        
        public ClienteASP.Oferta.ModeloOferta[] VerMisOfertas(string nombreUsuario) {
            return base.Channel.VerMisOfertas(nombreUsuario);
        }
        
        public ClienteASP.Oferta.ModeloOferta[] VerOfertasDelProducto(double idProducto) {
            return base.Channel.VerOfertasDelProducto(idProducto);
        }
        
        public void EscogerEstasOfertas(ClienteASP.Oferta.ModeloOferta[] ofertasGanadoras, ClienteASP.Oferta.ModeloOferta[] ofertasPerdedoras) {
            base.Channel.EscogerEstasOfertas(ofertasGanadoras, ofertasPerdedoras);
        }
    }
}
